/*
 * Data Universe
 * This is a sample Data Universe server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: datumgeek@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.technicalmedia.data.universe.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.*;
import java.util.Objects;

/**
 * Moon
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-06-28T05:23:16.947-06:00")
public class Moon   {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("orderFromPlanet")
  private Integer orderFromPlanet = null;

  @JsonProperty("size")
  private Double size = null;

  public Moon id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Moon name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @JsonProperty("name")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Moon orderFromPlanet(Integer orderFromPlanet) {
    this.orderFromPlanet = orderFromPlanet;
    return this;
  }

   /**
   * Get orderFromPlanet
   * @return orderFromPlanet
  **/
  @JsonProperty("orderFromPlanet")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public Integer getOrderFromPlanet() {
    return orderFromPlanet;
  }

  public void setOrderFromPlanet(Integer orderFromPlanet) {
    this.orderFromPlanet = orderFromPlanet;
  }

  public Moon size(Double size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @JsonProperty("size")
  @ApiModelProperty(value = "")
  public Double getSize() {
    return size;
  }

  public void setSize(Double size) {
    this.size = size;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Moon moon = (Moon) o;
    return Objects.equals(this.id, moon.id) &&
        Objects.equals(this.name, moon.name) &&
        Objects.equals(this.orderFromPlanet, moon.orderFromPlanet) &&
        Objects.equals(this.size, moon.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, orderFromPlanet, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Moon {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orderFromPlanet: ").append(toIndentedString(orderFromPlanet)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

